version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db_v1
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - motor_net

  mosquitto_broker:
    image: eclipse-mosquitto
    container_name: mosquitto_broker_v1
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped
    networks:
      - motor_net

  sensor_generator_service:
    image: sensor_generator_image:latest
    container_name: sensor_generator_v1
    depends_on:
      - mosquitto_broker
      - mongo_db
    restart: on-failure
    environment:
      - MONGO_URI=mongodb+srv://oussama:Oussama123@cluster0.jsz12tv.mongodb.net/
      - MQTT_BROKER=mosquitto_broker_v1
      - MQTT_PORT=1883
    networks:
      - motor_net

  edge_processor_service:
    image: edge_processor_image:latest
    container_name: edge_processor_v1
    depends_on:
      - mosquitto_broker
      - mongo_db
    volumes:
      - ./model/motor_model_xgb.model:/app/motor_model_xgb.model:ro
      - ./model/label_mapping_xgb.json:/app/label_mapping_xgb.json:ro
    restart: on-failure
    environment:
      - MQTT_BROKER=mosquitto_broker_v1
      - MQTT_PORT=1883
    networks:
      - motor_net

  streamlit_dashboard_service:
    image: streamlit_dashboard_image:latest
    container_name: streamlit_dashboard_v1
    ports:
      - "8501:8501"
    depends_on:
      - mosquitto_broker
      - mongo_db
    restart: on-failure
    environment:
      - MQTT_BROKER=mosquitto_broker_v1
      - MQTT_PORT=1883
    networks:
      - motor_net

volumes:
  mongo_data:

networks:
  motor_net:
    external: true
